captainVersion: 4

services:
    arguman:
        image: argumanorg/arguman:latest
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - DATABASE_URL=postgres://arguman:password@db:5432/arguman
        ports:
            - 3000:3000
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: arguman
            POSTGRES_PASSWORD: password
            POSTGRES_DB: arguman
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    data:
    db_data:

caproverOneClickApp:
    description: Arguman is a platform for creating and sharing structured arguments.
    variables:
        - id: 'database_password'
          label: 'Database Password'
          defaultValue: 'password'
          description: 'Password for the PostgreSQL database.'
          type: 'password'
    instructions:
        start: >-
            1. Fill in the database password.
            2. Deploy the app.
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: 'Arguman'
    isOfficial: false
    containerHttpPort: 3000
    containerPort: 3000
    httpPort: 80
