captainVersion: 4
services:
    $$cap_appname-db:
        image: postgres:$$cap_postgres_version
        restart: always
        environment:
            POSTGRES_DB: gitea
            POSTGRES_USER: gitea
            POSTGRES_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'
    $$cap_appname:
        depends_on:
            - $$cap_appname-db
        image: gitea/gitea:$$cap_gitea_version
        volumes:
            - $$cap_appname-data:/data
        restart: always
        environment:
            RUN_MODE: prod
            DB_TYPE: postgres
            DB_HOST: srv-captain--$$cap_appname-db:5432
            DB_USER: gitea
            DB_PASSWD: $$cap_db_pass
        caproverExtra:
            containerHttpPort: '3000'
caproverOneClickApp:
    variables:
        - id: $$cap_db_pass
          label: Postgres Root password
          defaultValue: $$cap_gen_random_hex(10)
          description: ''
          validRegex: /.{1,}/
        - id: $$cap_gitea_version
          label: Gitea Version
          defaultValue: '1.21.1'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/gitea/gitea/tags
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_postgres_version
          label: Postgres Version
          defaultValue: '16.4'
          description: Check out their Docker page for the valid tags https://hub.docker.com/_/postgres
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: >-
            A painless self-hosted Git service. Gitea is a community managed fork of Gogs.

            Enter your Gitea Configuration parameters and click on next. A Postgres (database) and a Gitea container will be created for you. The process will take about a minute to finish.
        end: >
            Gitea is deployed and available as $$cap_appname.

            Be sure to change 'Server domain' to `$$cap_root_domain` during initial setup otherwise you may experience issues.

            Since Gitea is running inside a container, you can optionally map a port (not 22) of the host to port 22 of the container, if you want to use git commands over SSH. You can perform port mapping in your CapRover dashboard, in App Config section.

            IMPORTANT: It will take up to 2 minutes for Gitea to be ready. Before that, you might see 502 error page.
    displayName: 'Gitea'
    isOfficial: true
    description: Gitea is a software package for hosting software development using Git as well as bug tracking, wikis and code review
    documentation: Taken from https://hub.docker.com/r/gitea/gitea/
